import Head from "next/head"
import Footer from "./Footer"
import Header from "./Header"

/* que es children en react */
const Layout = ({children}) => {
  return (
    <div>
      <Head>
        <title>LairDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      {children}
      <Footer/>

    </div>
  )
}

export default Layout